<?php
$G_DATABSE_HOSTNAME = "localhost";
$G_DATABSE_USERNAME = "root";
$G_DATABSE_PASSWORD = "";
$G_DATABSE_DATABASE_NAME = "voteblock";

$G_VOTERS_TABLE = "voter";
$G_BOOTH_TABLE = "booth";
$G_OPTIONS_TABLE = "options";

$G_ENCRYPTION_ALGO = "AES-128-CTR";
$G_ENCRYPTION_PASSPHRASE = "helloVoter2023";
$G_ENCRYPTION_IV = "0123456789012345";
